name: Frappe MQTT

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  frappe-mqtt:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.6
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis-cache:
        image: redis:alpine
        ports:
          - 6379:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 6380:6379
      redis-socketio:
        image: redis:alpine
        ports:
          - 6381:6379

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
          sudo apt-get install -y nodejs npm redis-server xvfb libssl-dev wkhtmltopdf mariadb-client mosquitto-clients mosquitto curl jq
          sudo apt -y install git build-essential libffi-dev libssl-dev curl pv
          pip install frappe-bench

      - name: Init bench and get Frappe
        run: |
          bench init --frappe-branch version-15 frappe-bench
          cd frappe-bench
          bench get-app https://github.com/mymi14s/frappe_mqtt

      - name: Create site
        run: |
          cd frappe-bench
          bench new-site site.local --mariadb-root-password root --admin-password administrator --no-mariadb-socket
          bench use site.local
          bench --site site.local install-app frappe_mqtt
          sudo bench setup production $USER
          

      - name: Insert MQTT Broker and Topic
        run: |
          cd frappe-bench
          bench migrate
          bench --site site.local execute frappe_mqtt.scripts.ci.create_data

      - name: Test MQTT Publish + Subscribe
        run: |
          # subscribe in background
          mosquitto_sub -h localhost -p 1883 -t "frappe/hello" -C 1 -W 10 > received.txt &
          sleep 2
          # publish message
          mosquitto_pub -h localhost -p 1883 -t "frappe/hello" -m '{"name":"mymi1"}'
          sleep 5
          echo "Received payload:"
          cat received.txt
          grep '"name":"mymi1"' received.txt

      - name: Test Webhook endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep 200
